defaults: &defaults
  docker:
    - image: 'circleci/node:latest'
  working_directory: ~/tmp/circlci-now
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/circlci-now
      - restore_cache:
          keys:
            - 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - 'yarn-cache-{{ .Branch }}'
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  deploy_frontend:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run: sudo yarn global add now
      - deploy:
          name: Deploy & Alias
          command: |
            cd Frontend
            now -f -t ${ZEIT_TOKEN} --scope floatingdots
            now alias staging.floatingdots.com -t ${ZEIT_TOKEN} --scope floatingdots
workflows:
  version: 2
  frontend:
    jobs:
      - checkout
      - deploy_frontend:
          requires:
            - checkout
          filters:
            branches:
              only: master
